### 异常 Exceptions

定义:异常是一个事件，在执行过程中发生，扰乱了程序指令的正常流程。

The object, called an exception object, contains information about the error,
including its type and the state of the program when the error occurred.
Creating an exception object and handing it to the runtime system is
called throwing an exception.

对象，称为异常对象，包含错误信息，包括错误发生时程序的类型和状态。

创建一个异常对象并将其传递给运行时系统是调用引发异常。

![image-20201029200704319](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029200704319.png)

运行时系统在调用堆栈中搜索包含可以处理异常的代码块。这段代码是调用异常处理程序exception handler.。

The search begins with the method in which the error occurred and
proceeds through the call stack in the reverse order in which the
methods were called.

搜索从发生错误的方法开始，并按照调用方法的相反顺序通过调用堆栈进行。

![image-20201029201116832](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029201116832.png)

The Catch or Specify Requirement

The code that might throw certain exceptions must be enclosed by
either of the following:
• **A try statement that catches the exception. The try must provide a**
**handler for the exception.**
• A method that specifies that it can throw the exception. **The**
**method must provide a throws clause that lists the exception**.
• **Code that fails to honor the Catch or Specify Requirement will not**
**compile.**
• **Not all exceptions are subject to the Catch or Specify Requirement.**

三种异常

![image-20201029201638631](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029201638631.png)

> **Checked Exception**:编译时进行检查
>
> These are exceptional conditions that a well-written application should
> anticipate and recover from.
>
> 这些都是异常情况，编写良好的应用程序应该预见到这些情况并从中恢复。
>
> **Error**：硬件或系统故障
>
> These are exceptional conditions that are external to the application,
> and that the application usually cannot anticipate or recover from.
>
> 这些是应用程序外部的异常条件，应用程序通常无法预测或从中恢复。
>
> **Runtime Exception**
>
> These are exceptional conditions that are internal to the application,
> and that the application usually cannot anticipate or recover from.
>
> 这些是应用程序内部的异常条件，应用程序通常无法预测或从中恢复。
>
> These usually indicate programming bugs, such as logic errors or
> improper use of an API.
>
> 这些通常表示编程错误，如逻辑错误或API的不当使用。

All exceptions are checked exceptions, **except for** those indicated by
**Error, RuntimeException, and their subclasses**

**Errors and runtime exceptions** are collectively known as **unchecked exceptions.**

**IndexOutOfBoundsException is an unchecked exception**

**IOException is an checked exception**

![image-20201029202833970](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029202833970.png)

**try**：contains one or more legal lines of code that could throw an exception.

If an exception occurs within the try block, that exception is handled
by an exception handler associated with it. To associate an exception
handler with a try block, you must put a catch block after it.

如果在try块中发生异常，则该异常由与其关联的异常处理程序处理。要将异常处理程序与一个try块关联，您必须在它之后放置一个catch块。

----

**catch**：Each catch block is an exception handler and handles the type of
exception indicated by its argument

每个catch块都是一个异常处理程序，并处理由其参数指示的异常类型

They can do error recovery, prompt the user to make a decision, or
propagate the error up to a higher-level handler using chained
exceptions.

它们可以进行错误恢复、提示用户做出决策，或者使用链锁异常将错误传播到更高级别的处理程序。

---

**finally**：The finally block always executes when the try block exits.

finally块总是在**try块退出时执行**

![image-20201029203348421](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029203348421.png)

throw：Any code can throw an exception

Regardless of what throws the exception, it's always thrown with
the throw statement.
public void writeList() **throws** **IOException** {}

![image-20201029204049688](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029204049688.png)

创造自己的异常类

![image-20201029204212601](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029204212601.png)

![image-20201029204229034](https://gitee.com/sunnyzq/my-image-hosting-service/raw/master/img//image-20201029204229034.png)

---

- If a client can reasonably be expected to **recover from** an exception,
  make it a **checked exception**.
- If a client **cannot do anything to recover from the exception,** make it an
  **unchecked exception**.

可恢复的--checked  exception   不可恢复的 --unchecked exception

---

**Advantages of Exceptions 异常的优点**

Advantage 1: Separating Error-Handling Code from "Regular" Code

将错误处理代码与“常规”代码分离

Advantage 2: Propagating Errors Up the Call Stack  

将错误传播到调用堆栈上

Advantage 3: Grouping and Differentiating Error Types

分组和区分错误类型

----

**Summary**

• A program can use exceptions to indicate that an error occurred.
• To throw an exception, use the throw statement and provide it with an
exception object — a descendant of Throwable—to provide
information about the specific error that occurred.
• A method that throws an uncaught, checked exception must include
a throws clause in its declaration

抛出未捕获的、检查过的异常的方法必须在声明中包含一个throws子句。

A program can **catch exceptions by using a combination of**
the **try, catch, and finally blocks.**

– The try block identifies a block of code in which an exception can
occur.
– The catch block identifies a block of code, known as an exception
handler, that can handle a particular type of exception.
– The finally block identifies a block of code that is guaranteed to
execute, and is the right place to **close files, recover resources, and**
**otherwise clean up after the code enclosed in the try block.**
– **The try statement should contain at least one catch block or**
**a finally block and may have multiple catch blocks.**

try块标识可以发生异常的代码块。

catch块标识一个代码块，称为异常处理程序，可以处理特定类型的异常。

finally块标识了保证执行的代码块，并且是关闭文件、恢复资源以及在try块中包含的代码之后进行清理的正确位置。

**try语句应该至少包含一个catch块或一个finally块，并且可能有多个catch块。**

